var fields = {
    "order_name": "Main Contact Name",
    "order_email": "Email Address",
	"order_phone_code": "Phone Code",
    "order_phone_number": "Phone Number",
    "order_street_address": "Street Address",
    "order_city": "City",
    "order_country": "Country",
    
    "order_company_name_1": "Name 1",
	"order_company_name_2": "Name 2",
	"order_company_name_3": "Name 3",
    "order_nature_of_business": "Proposed Business Activity",
	"first-jur": "Jurisdiction",
	"second-jur": "Jurisdiction",
    "order_number_of_shares": "Number of Shares",
    "vpsh-field": "Value per Share",
	"order_records_location": "Location of the Financial Records of the Company",
	
	"director_name": "Full Name",
	"director_address": "Residential Address",
	"director_registration_no": "Passport No. and Place of Issue",
	"director_day": "Day",
	"director_month": "Month",
	"director_year": "Year",
	"director_shareholder_shares_number": "Number of Shares to be issued",
	"director_ultimate_owner_shares": "Number of Shares Held",
	"director_ultimate_owner_source": "Source of Funds",
	
	"shareholder_name": "Full Name",
	"shareholder_address": "Residential Address",
	"shareholder_registration_no": "Passport No. and Place of Issue",
	"shareholder_day": "Day",
	"shareholder_month": "Month",
	"shareholder_year": "Year",
	"shareholder_shares_number": "Number of Shares to be issued",
	"shareholder_ultimate_owner_shares": "Number of Shares Held",
	"shareholder_ultimate_owner_source": "Source of Wealth",
	
	"ultimate_owner_name": "Full Name",
	"ultimate_owner_address": "Residential Address",
	"ultimate_owner_passport_no": "Passport No. &amp; Place of Issue",
	"ultimate_owner_day": "Day",
	"ultimate_owner_month": "Month",
	"ultimate_owner_year": "Year",
	"ultimate_owner_shares": "Number of Shares Held",
	"ultimate_owner_ultimate_owner_shares": "Number of Shares Held",
	"ultimate_owner_source": "Source of Wealth",
	"ultimate_owner_ultimate_owner_source": "Source of Wealth",
	
	"first-pref-jur": "Preferred Jurisdiction",
	"second-pref-jur": "Preferred Jurisdiction",
	"order_required_currency": "Blabla 1",
	"order_authorised_signatory": "Blabla 2",
	"order_method_of_signature": "Blabla 3",
    "order_regions_countries_list": "Blabla 4",
    "order_nc_of_remitters": "Blabla 5",
    "order_nc_of_beneficiaries": "Blabla 6",
	"order_turnover": "Blabla 7",
	"order_transfers_into": "Blabla 8",
	"order_transfers_out_of": "Blabla 9"
    
    
}
var countries = new Array(
		"Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antarctica",
		"Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
		"Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus",
		"Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia",
		"Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria",
		"Burkina Faso", "Burma", "Burundi", "Cambodia", "Cameroon", "Canada",
		"Cape Verde", "Central African Republic", "Chad", "Chile", "China",
		"Colombia", "Comoros", "Congo, Democratic Republic",
		"Congo, Republic of the", "Costa Rica", "Cote d'Ivoire", "Croatia",
		"Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica",
		"Dominican Republic", "East Timor", "Ecuador", "Egypt", "El Salvador",
		"Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji",
		"Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana",
		"Greece", "Greenland", "Grenada", "Guatemala", "Guinea",
		"Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hong Kong", "Hungary",
		"Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel",
		"Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya",
		"Kiribati", "Korea, North", "Korea, South", "Kuwait", "Kyrgyzstan",
		"Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
		"Liechtenstein", "Lithuania", "Luxembourg", "Macedonia", "Madagascar",
		"Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands",
		"Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova",
		"Mongolia", "Morocco", "Monaco", "Mozambique", "Namibia", "Nauru",
		"Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria",
		"Norway", "Oman", "Pakistan", "Panama", "Papua New Guinea", "Paraguay",
		"Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania",
		"Russia", "Rwanda", "Samoa", "San Marino", "Sao Tome and Principe", 
		"Saudi Arabia", "Senegal", "Serbia and Montenegro", "Seychelles",
		"Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands",
		"Somalia", "South Africa", "Spain", "Sri Lanka", "Sudan", "Suriname",
		"Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan",
		"Tanzania", "Thailand", "Togo", "Tonga", "Trinidad and Tobago",
		"Tunisia", "Turkey", "Turkmenistan", "Uganda", "Ukraine",
		"United Arab Emirates", "United Kingdom", "United States", "Uruguay",
		"Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Zambia",
		"Zimbabwe"
);
var countries_without_pc = new Array(
		"Angola", "Antigua and Barbuda", "Bahamas", "Belize", "Benin",
		"Botswana", "Burkina Faso", "Burundi", "Cameroon",
		"Central African Republic", "Comoros", "Congo, Democratic Republic",
		"Congo, Republic of the", "Cote d'Ivoire", "Djibouti", "Dominica",
		"East Timor", "Equatorial Guinea", "Eritrea", "Fiji", "Gambia", "Ghana",
		"Grenada", "Guinea", "Guyana", "Hong Kong", "Ireland", "Jamaica",
		"Kenya", "Kiribati", "Korea, North", "Malawi", "Mali", "Mauritania",
		"Mauritius", "Nauru", "Panama", "Qatar", "Rwanda",
		"Sao Tome and Principe", "Saudi Arabia","Seychelles", "Sierra Leone",
		"Solomon Islands", "Somalia", "Suriname", "Syria", "Tanzania", "Tonga",
		"Trinidad and Tobago", "Uganda", "United Arab Emirates", "Vanuatu", 
		"Yemen", "Zimbabwe"
);

